### ISSUE TITLE
Add ACM Plus to Resources page

### ISSUE THREAD

**Issue by alex-bellon** [UTACM/TexasACM.org#182]

**Comment by rolsanmordua** [comment]
"Get the most out of ACM with ACM Plus membership! For $15 you will receive the latest ACM 2019-2020 t-shirt, have access to all Game Nights for the year, and gain discounts on lockers and soda (with tab rights). Join here (hyperlinked: https://www.texasacm.org/forms/joinPlus)!"

**Comment by rolsanmordua** [comment]
Hmm, I think a Resources page content re order is needed too:

From left to right, top to bottom:
- Become a member, Get Connected
- Résumé Book, CS 101
- Code of Conduct, Bylaws
- Join our Mentorship Program, Become an Officer (moving these down because these have since passed and happen once per semester at most)
- Human Resources Contact 

If y'all have ideas about how to re organize this page better, I'd be open to listening to some ideas. It's getting kinda long. But I think the grouping above will make things better and hopefully is what people access most (links at top).

**Comment by alex-bellon** [comment]
Yeah, I've been trying to fix this on one of the branches I have. I've been trying to redesign it too, since it's kind of visually confusing.
