### ISSUE TITLE
Redesign Simple Sign In to account for multiple events on a given day

### ISSUE THREAD

**Issue by rolsanmordua** [UTACM/TexasACM.org#87]

**Comment by rolsanmordua** [comment]
We have opted to stop embedding sign in forms on the website. Instead we are redirecting to the sign in form directly so that our users can autofill speeding up sign on time. We are keeping the code for SSI since it may be easily reusable for another feature in the future.

**Comment by ChiaHuaLu** [comment]
I learned something while doing my Cloud Project, which would be helpful to know if the team chooses to re-persuit an API like simple signins.

As you may recall, we abandoned this simple signin project because we could not get past CORS and some "Origin Header" error from Chrome. We were getting the same issue in our Cloud Project which involved accessing a API Gateway->Lambda Serverless Function->Database backend,

What we did to solve this issue was: Enable CORS to our endpoints in API Gateway, AND:
Add the following code chunk to the JSON object our Lambda returned:
